name: Deploy to ECR
# Updated ECR Repo week3-1 01/22

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build, test, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: clo835-week3-1
          IMAGE_TAG: v0.1
        run: |
          # Navigate to the directory containing the Dockerfile
          cd Chapter02/kubia/
          ls -ltra

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          echo "Running container for testing..."
          docker run -d -p 80:8080 --name nodeapp $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Waiting 10 seconds for the container to start..."
          sleep 10
          echo "Testing container with curl..."
          curl localhost -vvv || echo "Container test failed"

          echo "Stopping and cleaning up the container..."
          docker stop nodeapp && docker rm nodeapp

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
